<?php

require 'config/config.php';
require 'config/database.php';
$db = new Database();
$con =$db->conectar();

$sql = $con->prepare("SELECT id, nombre, precio FROM productos WHERE activo=1");
$sql->execute();
$resultado = $sql->fetchAll(PDO::FETCH_ASSOC);

//session_destroy();

//print_r($_SESSION);

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FIMETRONICA</title>
<link rel="stylesheet" href="css/bootstrap.min.css">
<script src="js/jquery-3.5.1.min.js"> </script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="css/style.css">
<!--<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&display=swap" rel="stylesheet" type='text/css'>-->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Kreon&display=swap" rel="stylesheet" type="text/css">
<link rel="icon" href="img/ordenador-personal.png" type="image/png">

</head>
<body>
	<!--audio-->
	<audio src="aud/sweetness.mp3"  autoplay="true" type="audio/mpeg"></audio>
	<!--< loop="3"embed src="aud/Ours Samplus - Capture loiseau.mp3" autostarty="true" loop="true" width="0px" height="0px">-->
   <!--navegador-->
 <header>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="background-color: rgb(110, 143, 181);">
	<a class="navbar-brand" href="index.php">
		<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0) -->
 		<img src="img/logo-oso.png" height="65px" width="65px">
			F I M E T R O N I C A
	</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item active"><a class="nav-link" href="index.php">Inicio</a></li>
			<li class="nav-item "><a class="nav-link" href="Contacto.php">Contacto</a></li>
	<!--		<li class="nav-item "><a class="nav-link" href="Galería.html">Videos</a></li> 
			<li class="nav-item "><a class="nav-link" href="Descargas.html">Equipo 2</a></li> -->
			<li class="nav-item "><a class="nav-link" href="Productos.php">Productos</a></li>
		 </ul>
	</div>
	   <a href="checkout.php" class="btn position-relative" aling="right">
            <img src="img/carrito.png" height="40px"><span id="num_cart" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-light"><?php echo $num_cart; ?></span>
        </a>
</nav>
<section class="textos-header">
		
	<h1>F I M E T R O N I C A</h1>
	<h1>Tienda de Electronica</h1>
</section>
<!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
<div class="wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>
</header>
<nav class="contenedor">
<main>
	<section class="contenedor-informacion">
		<h2 class="titulo">Sobre Nosotros</h2>
		<div class="contenedor-Informacion">

			<img src="img/Ilustracion1.png" heght="40%" width="30%" alt="" class="Informacion">
			<div class="contenedor-Text_i">

				<h3><span>1</span>¿Qué hacemos?</h3>
				<p>Somos una tienda web de electronica especialmente para estudiantes de ingeneria </p>
				<h3><span>2</span>¿Que podemos encontrar en ella?</h3>
				<p>Todo tipo de herramientas de electronica</p>
			</div>
		</div>
	</section>
	<!--CARDS RESPONSIVE-->
	<section class="cardsdeinfo"> <!--contenedor-->
		<h2 class="titulo">Herramientas mas populares</h2>
		<div class="container-card" >
			<div class="cards-info"> <!--card-->
				<div class="imgBox" data-text="FIMETRONICA"> <!--contenedor imagen-->
					<img src="img/Compu.png">
				</div>
					<div class="contenedor-cardinfo"><!--contenedor info-->
						<div>
						<h2 class="letra-card">Multimetro</h2>
							<p>Es una herramienta de diagnóstico estándar para los técnicos de las industrias eléctricas y electrónicas</p>
								<h4><span>1</span>Medicion Funcional - Medir la tensión de voltaje, corriente directa (DC), medición de la continuidad, la resistencia y el diodo</h4>
								<h4><span>2</span>Proteccion - Hay un fusible dentro y la forma segura para evitar la energía que se desborde.</h4>
				
								<h5>Para más información</h5>
									<a href="Productos.php" target="_BLANK" >Click Aquí</a>
							</div>	
					</div>
			</div>

			<div class="cards-info">
				<div class="imgBox" data-text="FIMETRONICA">
					<img src="img/aurdino.png">
				</div>
					<div class="contenedor-cardinfo">
						<div>
							<h2 class="letra-card">Arduino</h2>
							<p>Es una plataforma de hardware libre, nos referimos a que cualquier persona puede crear y modificar sus propias placas.</p>
								<h4><span>1</span>Arduino UNO R3 [A000066]</h4>
								<h4><span>2</span>Microcontrolador</h4>
								<h4><span>3</span>Plataforma de hardware libre</h4>
								<h5>Para más información</h5>
									<a href="Productos.php" target="_BLANK" >Click Aquí</a>
							</div>	
					</div>
			</div>

			<div class="cards-info">
				<div class="imgBox" data-text="FIMETRONICA">
					<img src="img/proto.png" >
				</div>
					<div class="contenedor-cardinfo">
						<div>
						<h2 class="letra-card">PROTOBOARD</h2>
							<p>Utilizada comúnmente para pruebas y prototipos temporales de circuitos. Se usa insertando las terminales de los dispositivos electrónicos.</p>
								<h4><span>1</span>MV ELECTRONICA</h4>
								<h4><span>2</span>PROTOBOARD BREADBOARD</h4>
								<h4><span>3</span>400 Puntos Blanca</h4>
								<h5>Para más información</h5>
									<a href="Productos.php" target="_BLANK" >Click Aquí</a>	
							</div>
					</div>
			</div>
		</div>
	</section>
	</nav>

	<section class="img-contenedor">
		<br>
			<h2 class="titulo">Otras Herramientas</h2>
		<div class="contenedor-imagen">
			<figure>
				<img src="img/cautin.png" alt="">
				<div class="capa">
					<h3 class="titulo">Cautín tipo lápiz</h3>
					<p> Sirve para soldar o unir metales en circuitos electrónicos.<br></p>
				</div>
			</figure>
			<figure>
				<img src="img/leds.png" alt="">
				<div class="capa">
					<h3 class="titulo">Leds de colores</h3>
					<p>Un diodo LED es un dispositivo que permite el paso de corriente en un solo sentido y que al ser polarizado emite un haz de luz.<br></p>
				</div>
			</figure>
			<figure>
				<img src="img/resistencia.png" alt="">
				<div class="capa">
					<h3 class="titulo">Resistores o Resistencias</h3>
					<p>Los resistores se utilizan en los circuitos para limitar el valor de la corriente o para fijar el valor de la tensión, según la Ley de Ohm<br></p>
				</div>
			</figure>
			<figure>
				<img src="img/capacitador.png" alt="">
				<div class="capa">
					<h3 class="titulo">Capacitadores</h3>
					<p>Un capacitor o condensador eléctrico es un dispositivo que se utiliza para almacenar energía (carga eléctrica) en un campo eléctrico interno. <br></p>
				</div>
			</figure>
			<!--</figure>-->
	<section class="Soluciones">
		<div class="contenedor">
			<h2 class="titulo">Uso con precaucion</h2>
			<div class="solucion-cont">
				<div class="solicion-ind">
					<img src="img/actualizar.png" alt="">
					<h3><span>1</span></h3>
					<p>Usar guantes. Evitar agarrar la punta con los dedos.</p>
				</div>
				<div class="solicion-ind">
					<img src="img/cuestionar.png" alt="">
					<h3><span>2</span></h3>
					<p><center>Usar guantes si es necesario.</center></p>
				</div>
				<div class="solicion-ind">
					<img src="img/creatividad.svg" alt="">
					<h3><span>3</span></h3>
					<p><center>Uso de lentes de seguridad.</center></p>
				</div>
			</div>
		</div>
	</section>
		</div>
	</section>
</main>
<footer>
	<!--div class="contenedor-footer">
		<div class="content-foo">
			<h4>Word</h4>
			<p>...</p>
		<div class="content-foo">
			<h4>Power Point</h4>
			<p>...</p>
		</div>
		<div class="content-foo">
			<h4>Excel</h4>
			<p>...</p>
		</div>
	</div-->
	<h2 class="titulo-final"> FACULTAD DE INGENIERÍA MECÁNICA Y ELÉCTRICA | EQUIPO 2 </h2>
</footer>


    
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    
</body>
</html>